spring.application.name=document-service

### DB ###
spring.datasource.url=jdbc:postgresql://localhost:5433/itq_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

### Liquibase ###
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

### submit-worker ###
workers.submit.enabled=true
workers.submit.batch-size=10
workers.submit.delay-ms=5000

### approve-worker ###
workers.approve.enabled=true
workers.approve.batch-size=10
workers.approve.delay-ms=5000

### log ###
logging.level.root=INFO
logging.level.ru.test.document_service=INFO