spring.application.name=document-service

### DB ###
spring.datasource.url=jdbc:postgresql://localhost:5432/itq_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false

### Liquibase ###
spring.liquibase.enabled=false

### submit-worker ###
workers.submit.enabled=true
workers.submit.batch-size=10
workers.submit.delay-ms=5000

### approve-worker ###
workers.approve.enabled=true
workers.approve.batch-size=10
workers.approve.delay-ms=5000

### log ###
logging.file.name=logs/document-service.log
logging.level.root=INFO
logging.level.ru.test.document_service=INFO
logging.level.ru.test.document_service.service.worker.DocumentWorkersScheduler=DEBUG
logging.level.ru.test.document_service.service.worker.DocumentWorkerService=DEBUG